#!/bin/sh
#
# @name Cessna airplane SITL for SXP
#
# @type Plane
#
# @maintainer Romain Chiappinelli <romain.chiap@gmail.com>

. ${R}etc/init.d/rc.fw_defaults

set MIXER AERT

# disable some checks to allow to fly:
# - with usb
param set-default CBRK_USB_CHK 197848
# - without real battery
param set-default CBRK_SUPPLY_CHK 894281
# - without safety switch
param set-default COM_PREARM_MODE 0
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_AIRSPD_CHK 162128
param set-default SYS_HAS_BARO 0
param set-default SYS_HAS_GPS 0
param set-default SYS_HAS_MAG 0

param set-default BAT_N_CELLS 3


param set SIH_VEHICLE_TYPE 1 	# sih as fixed wing
param set RWTO_TKOFF 1  # enable takeoff from runway (as opposed to launched)
